# global:
#     scrape_interval: 30s

# scrape_configs:
# - job_name: 'prometheus'
#   static_configs:
#   - targets: ['localhost:9090']

# - job_name: 'node'
#   scrape_interval: 10s
#   file_sd_configs:
#   - files:
#   - '/etc/prometheus/targets/targets.json'

# - job_name: 'node-low'
#   scrape_interval: 10s
#   static_configs:
#   - targets: ['192.168.56.108:9100']
global:
  scrape_interval: 30s

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: node
  file_sd_configs:
  - files:
    - /etc/prometheus/targets/targets.json
    refresh_interval: 5m
- job_name: node-low
  static_configs:
  - targets:
    - 192.168.56.108:9100