---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: docker-local-storage
  resources:
    requests:
      storage: 1Gi
