name: Hello World

on: [push]

jobs:
  say-hello:
    runs-on: sirius-linux

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Say Hello
      run: echo "Hello, World!"
